// mobile/src/components/StateChip.tsx
/**
 * State chip za prikaz statusa naloga.
 *
 * Mapping je ugovoran, isti na webu i mobile (docs/API.md "Konvencije" i
 * design/README.md "Job lifecycle"):
 *   novo      = ink border  / white fill / ink tekst
 *   zakazano  = bark border / ivory fill / bark tekst
 *   u_toku    = ember border/ ember fill / ivory tekst
 *   zavrseno  = sand border / sand fill  / ink tekst
 *   garancija = ink border  / ink fill   / ivory tekst
 */

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { type ChipState, stateChipStyles, typeScale } from '../theme/tokens';

const CHIP_LABELS: Record<ChipState, string> = {
  novo: 'Novo',
  zakazano: 'Zakazano',
  u_toku: 'U toku',
  zavrseno: 'Završeno',
  garancija: 'Garancija',
};

interface StateChipProps {
  state: ChipState;
  /** Prepiši prikazani tekst; podrazumijevano koristi CHIP_LABELS. */
  label?: string;
}

export function StateChip({ state, label }: StateChipProps) {
  const chipStyle = stateChipStyles[state];

  return (
    <View
      style={[
        styles.chip,
        { backgroundColor: chipStyle.fill, borderColor: chipStyle.border },
      ]}
    >
      <Text style={[styles.label, { color: chipStyle.text }]}>
        {label ?? CHIP_LABELS[state]}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  chip: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    // Nema borderRadius.
  },
  label: {
    ...typeScale.eyebrow,
    letterSpacing: 0.5,
  },
});

export default StateChip;

// web/resources/js/components/StateChip.vue
<script setup>
import { computed } from 'vue';

// Mapping stanja naloga na chip stil. Isti mapping koristi i admin faza,
// pa se ovaj fajl ne mijenja bez razloga koji vrijedi za oba surface-a.
// Izvor: design/README.md, "State chip styling" i docs/API.md konvencije.
const STYLES = {
  novo: { border: 'var(--ink)', bg: 'var(--white)', color: 'var(--ink)', label: 'Novo' },
  zakazano: { border: 'var(--bark)', bg: 'var(--ivory)', color: 'var(--bark)', label: 'Zakazano' },
  u_toku: { border: 'var(--ember)', bg: 'var(--ember)', color: 'var(--ivory)', label: 'U toku' },
  zavrseno: { border: 'var(--sand)', bg: 'var(--sand)', color: 'var(--ink)', label: 'Završeno' },
  garancija: { border: 'var(--ink)', bg: 'var(--ink)', color: 'var(--ivory)', label: 'Garancija' },
};

const props = defineProps({
  // novo | zakazano | u_toku | zavrseno | garancija
  state: { type: String, required: true },
  label: { type: String, default: '' },
});

const style = computed(() => STYLES[props.state] || STYLES.novo);
</script>

<template>
  <span
    class="num"
    :style="{
      display: 'inline-flex',
      alignItems: 'center',
      border: `1px solid ${style.border}`,
      background: style.bg,
      color: style.color,
      padding: '4px 9px',
      fontSize: '12px',
      fontWeight: 600,
      letterSpacing: '.04em',
      whiteSpace: 'nowrap',
    }"
  >{{ label || style.label }}</span>
</template>
